"""added login history

Revision ID: ee7c77761253
Revises: 42b14c8de703
Create Date: 2021-02-08 21:09:22.849085

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee7c77761253'
down_revision = '42b14c8de703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('device_idx', 'user_login_history', ['device'], unique=False)
    op.create_index(op.f('ix_user_login_history_user_id'), 'user_login_history', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_user_login_history_user_id'), table_name='user_login_history')
    op.drop_index('device_idx', table_name='user_login_history')
    op.drop_table('user_login_history')
    # ### end Alembic commands ###
